create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  role text not null default 'seeker' check (role in ('seeker','employer','admin')),
  full_name text not null default '',
  email text,
  mobile text,
  location text,
  skills text,
  qualification text,
  experience text,
  company_details text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.employers (
  id uuid primary key references public.profiles(id) on delete cascade,
  company_name text not null default '',
  company_details text,
  website text,
  verified boolean not null default false,
  created_at timestamptz not null default now()
);

create table if not exists public.job_categories (
  id bigint generated by default as identity primary key,
  name text unique not null
);

create table if not exists public.job_locations (
  id bigint generated by default as identity primary key,
  name text unique not null
);

create table if not exists public.jobs (
  id uuid primary key default gen_random_uuid(),
  employer_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  company text not null,
  category text,
  location text not null,
  salary text,
  type text,
  experience text,
  qualification text,
  skills text,
  description text not null,
  deadline date,
  image_url text,
  status text not null default 'pending' check (status in ('pending','approved','rejected','disabled')),
  reject_reason text,
  approved_by uuid references public.profiles(id),
  approved_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);create table if not exists public.job_applications (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.jobs(id) on delete cascade,
  seeker_id uuid not null references public.profiles(id) on delete cascade,
  cover_note text,
  resume_url text,
  status text not null default 'applied' check (status in ('applied','shortlisted','interview','selected','rejected')),
  employer_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(job_id,seeker_id)
);

create table if not exists public.saved_jobs (
  id uuid primary key default gen_random_uuid(),
  job_id uuid not null references public.jobs(id) on delete cascade,
  seeker_id uuid not null references public.profiles(id) on delete cascade,
  created_at timestamptz not null default now(),
  unique(job_id,seeker_id)
);

create table if not exists public.consultancies (
  id bigint generated by default as identity primary key,
  name text not null,
  location text,
  phone text,
  website text,
  description text,
  created_at timestamptz not null default now()
);

create table if not exists public.notifications (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references public.profiles(id) on delete cascade,
  title text not null,
  message text not null,
  read boolean not null default false,
  created_at timestamptz not null default now()
);

create index if not exists jobs_status_idx on public.jobs(status);
create index if not exists jobs_employer_idx on public.jobs(employer_id);
create index if not exists jobs_location_idx on public.jobs(location);
create index if not exists jobs_category_idx on public.jobs(category);
create index if not exists applications_job_idx on public.job_applications(job_id);
create index if not exists applications_seeker_idx on public.job_applications(seeker_id);create or replace function public.is_admin()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='admin') $$;

create or replace function public.is_employer()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='employer') $$;

create or replace function public.is_seeker()
returns boolean language sql stable security definer set search_path=public
as $$ select exists(select 1 from public.profiles where id=auth.uid() and role='seeker') $$;

create or replace function public.handle_new_user()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  insert into public.profiles(id,email,full_name,role)
  values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name',''),
    case when coalesce(new.raw_user_meta_data->>'role','seeker')='employer'
      then 'employer' else 'seeker' end)
  on conflict(id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.employers enable row level security;
alter table public.jobs enable row level security;
alter table public.job_applications enable row level security;
alter table public.saved_jobs enable row level security;
alter table public.job_categories enable row level security;
alter table public.job_locations enable row level security;
alter table public.consultancies enable row level security;
alter table public.notifications enable row level security;drop policy if exists profiles_select_own_admin on public.profiles;
create policy profiles_select_own_admin on public.profiles for select using (id=auth.uid() or public.is_admin());

drop policy if exists profiles_update_own_admin on public.profiles;
create policy profiles_update_own_admin on public.profiles for update using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());

drop policy if exists employers_own_admin on public.employers;
create policy employers_own_admin on public.employers for all using (id=auth.uid() or public.is_admin()) with check (id=auth.uid() or public.is_admin());

drop policy if exists jobs_public_approved on public.jobs;
create policy jobs_public_approved on public.jobs for select using (status='approved' or employer_id=auth.uid() or public.is_admin());

drop policy if exists jobs_employer_insert on public.jobs;
create policy jobs_employer_insert on public.jobs for insert with check (employer_id=auth.uid() and public.is_employer());

drop policy if exists jobs_employer_update on public.jobs;
create policy jobs_employer_update on public.jobs for update using (employer_id=auth.uid() or public.is_admin()) with check (employer_id=auth.uid() or public.is_admin());

drop policy if exists jobs_admin_delete on public.jobs;
create policy jobs_admin_delete on public.jobs for delete using (public.is_admin());

drop policy if exists applications_seeker_insert on public.job_applications;
create policy applications_seeker_insert on public.job_applications for insert
with check (seeker_id=auth.uid() and public.is_seeker()
  and exists(select 1 from public.jobs j where j.id=job_id and j.status='approved'));

drop policy if exists applications_read on public.job_applications;
create policy applications_read on public.job_applications for select
using (seeker_id=auth.uid() or public.is_admin() or exists(
  select 1 from public.jobs j where j.id=job_id and j.employer_id=auth.uid()
));drop policy if exists applications_update on public.job_applications;
create policy applications_update on public.job_applications for update
using (public.is_admin() or exists(select 1 from public.jobs j where j.id=job_id and j.employer_id=auth.uid()))
with check (public.is_admin() or exists(select 1 from public.jobs j where j.id=job_id and j.employer_id=auth.uid()));

drop policy if exists saved_own on public.saved_jobs;
create policy saved_own on public.saved_jobs for all
using (seeker_id=auth.uid()) with check (seeker_id=auth.uid() and public.is_seeker());

drop policy if exists categories_public on public.job_categories;
create policy categories_public on public.job_categories for select using (true);

drop policy if exists locations_public on public.job_locations;
create policy locations_public on public.job_locations for select using (true);

drop policy if exists consultancies_public on public.consultancies;
create policy consultancies_public on public.consultancies for select using (true);

drop policy if exists notifications_own on public.notifications;
create policy notifications_own on public.notifications for select using (user_id=auth.uid() or public.is_admin());

drop policy if exists notifications_update on public.notifications;
create policy notifications_update on public.notifications for update using (user_id=auth.uid() or public.is_admin());

insert into public.job_categories(name) values
('Computer'),('Security'),('Delivery'),('Retail'),('Technician'),('Hotel')
on conflict do nothing;

insert into public.job_locations(name) values
('Siliguri'),('Matigara'),('Bagdogra'),('Sevoke Road'),('Pradhan Nagar')
on conflict do nothing;

create or replace function public.sync_employer_profile()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  if new.role='employer' then
    insert into public.employers(id,company_name,company_details)
    values(new.id,coalesce(new.full_name,''),new.company_details)
    on conflict(id) do update set company_name=excluded.company_name,
      company_details=excluded.company_details;
  end if;
  return new;
end;
$$;

drop trigger if exists sync_employer_profile_trigger on public.profiles;
create trigger sync_employer_profile_trigger
after insert or update of role,full_name,company_details on public.profiles
for each row execute procedure public.sync_employer_profile();

-- After registering the first account, assign it admin:
-- update public.profiles set role='admin' where email='YOUR-ADMIN-EMAIL@example.com';create or replace function public.protect_profile_role()
returns trigger language plpgsql security definer set search_path=public
as $$
begin
  if auth.uid() is not null and old.role is distinct from new.role
     and not public.is_admin() then
    new.role := old.role;
  end if;
  return new;
end;
$$;

drop trigger if exists protect_profile_role_trigger on public.profiles;
create trigger protect_profile_role_trigger
before update on public.profiles
for each row execute procedure public.protect_profile_role();